/**
 * Biblioteca curada de ícones Lucide disponíveis para representar categorias.
 * Mantida como fonte única de verdade para o seletor no painel admin e para
 * a renderização em <CategoryIcon />.
 */
import {
  Apple,
  Beef,
  ShoppingBasket,
  Milk,
  Croissant,
  CupSoda,
  Coffee,
  Cookie,
  Candy,
  Snowflake,
  Sparkles,
  SprayCan,
  Package,
  Pizza,
  Sandwich,
  IceCream,
  Cake,
  EggFried,
  Fish,
  Drumstick,
  Ham,
  Wheat,
  Carrot,
  Cherry,
  Grape,
  Banana,
  Salad,
  Soup,
  Wine,
  Beer,
  Flower2,
  Leaf,
  Baby,
  PawPrint,
  Pill,
  HeartPulse,
  Bath,
  ShowerHead,
  Trash2,
  WashingMachine,
  Utensils,
  ShoppingCart,
  Store,
  type LucideIcon,
} from "lucide-react";

export const LUCIDE_PRESET: Record<string, LucideIcon> = {
  apple: Apple,
  beef: Beef,
  "shopping-basket": ShoppingBasket,
  milk: Milk,
  croissant: Croissant,
  "cup-soda": CupSoda,
  coffee: Coffee,
  cookie: Cookie,
  candy: Candy,
  snowflake: Snowflake,
  sparkles: Sparkles,
  "spray-can": SprayCan,
  package: Package,
  pizza: Pizza,
  sandwich: Sandwich,
  "ice-cream": IceCream,
  cake: Cake,
  "egg-fried": EggFried,
  fish: Fish,
  drumstick: Drumstick,
  ham: Ham,
  wheat: Wheat,
  carrot: Carrot,
  cherry: Cherry,
  grape: Grape,
  banana: Banana,
  salad: Salad,
  soup: Soup,
  wine: Wine,
  beer: Beer,
  flower: Flower2,
  leaf: Leaf,
  baby: Baby,
  paw: PawPrint,
  pill: Pill,
  "heart-pulse": HeartPulse,
  bath: Bath,
  shower: ShowerHead,
  trash: Trash2,
  laundry: WashingMachine,
  utensils: Utensils,
  cart: ShoppingCart,
  store: Store,
};

export const LUCIDE_PRESET_NAMES = Object.keys(LUCIDE_PRESET);

export function resolveLucide(name: string | undefined | null): LucideIcon | null {
  if (!name) return null;
  return LUCIDE_PRESET[name] ?? null;
}
