/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemPermissaoRouteImport } from './routes/sem-permissao'
import { Route as ResgatarRouteImport } from './routes/resgatar'
import { Route as RecuperarPinRouteImport } from './routes/recuperar-pin'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as MinhasLicencasRouteImport } from './routes/minhas-licencas'
import { Route as MelhoresPrecosRouteImport } from './routes/melhores-precos'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LojistaRouteImport } from './routes/lojista'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as ComprarLicencaRouteImport } from './routes/comprar-licenca'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as ComparadorRouteImport } from './routes/comparador'
import { Route as ColaborarRouteImport } from './routes/colaborar'
import { Route as CestaBasicaRouteImport } from './routes/cesta-basica'
import { Route as CestaRouteImport } from './routes/cesta'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as AppRouteImport } from './routes/app'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as ProdutoPublicoSlugRouteImport } from './routes/produto-publico.$slug'
import { Route as LojaIdRouteImport } from './routes/loja.$id'
import { Route as HistoricoScansRouteImport } from './routes/historico.scans'
import { Route as HistoricoProdutosRouteImport } from './routes/historico.produtos'
import { Route as HistoricoIdRouteImport } from './routes/historico.$id'
import { Route as CotacaoIdRouteImport } from './routes/cotacao.$id'
import { Route as ComprovanteIdRouteImport } from './routes/comprovante.$id'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as CShareIdRouteImport } from './routes/c.$shareId'
import { Route as AdminSinonimosRouteImport } from './routes/admin_.sinonimos'
import { Route as AdminReportsRouteImport } from './routes/admin_.reports'
import { Route as AdminRankCheckRouteImport } from './routes/admin_.rank-check'
import { Route as AdminPrecosRouteImport } from './routes/admin_.precos'
import { Route as AdminMetricasRouteImport } from './routes/admin_.metricas'
import { Route as AdminLoteInserirRouteImport } from './routes/admin_.lote-inserir'
import { Route as AdminImageJobsRouteImport } from './routes/admin_.image-jobs'
import { Route as AdminIconesCategoriaRouteImport } from './routes/admin_.icones-categoria'
import { Route as AdminCupomLoteRouteImport } from './routes/admin_.cupom-lote'
import { Route as AdminCupomRouteImport } from './routes/admin_.cupom'
import { Route as AdminConsistenciaRouteImport } from './routes/admin_.consistencia'
import { Route as AdminCoberturaRouteImport } from './routes/admin_.cobertura'
import { Route as AdminCatalogoRouteImport } from './routes/admin_.catalogo'
import { Route as AdminAuditoriaRouteImport } from './routes/admin_.auditoria'
import { Route as AdminAnalyticsRouteImport } from './routes/admin_.analytics'
import { Route as AdminGestaoRouteImport } from './routes/admin/gestao'
import { Route as ApiAdminCatalogImageRouteImport } from './routes/api/admin/catalog-image'
import { Route as AdminCoberturaIdRouteImport } from './routes/admin_.cobertura.$id'
import { Route as LojaIdProdutoSlugRouteImport } from './routes/loja.$id.produto.$slug'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago/webhook'
import { Route as ApiPublicHooksRefreshCatalogImagesRouteImport } from './routes/api/public/hooks/refresh-catalog-images'
import { Route as ApiPublicHooksDrainCatalogImagesRouteImport } from './routes/api/public/hooks/drain-catalog-images'
import { Route as ApiPublicHooksCollabInboundRouteImport } from './routes/api/public/hooks/collab-inbound'

const SemPermissaoRoute = SemPermissaoRouteImport.update({
  id: '/sem-permissao',
  path: '/sem-permissao',
  getParentRoute: () => rootRouteImport,
} as any)
const ResgatarRoute = ResgatarRouteImport.update({
  id: '/resgatar',
  path: '/resgatar',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarPinRoute = RecuperarPinRouteImport.update({
  id: '/recuperar-pin',
  path: '/recuperar-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasLicencasRoute = MinhasLicencasRouteImport.update({
  id: '/minhas-licencas',
  path: '/minhas-licencas',
  getParentRoute: () => rootRouteImport,
} as any)
const MelhoresPrecosRoute = MelhoresPrecosRouteImport.update({
  id: '/melhores-precos',
  path: '/melhores-precos',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LojistaRoute = LojistaRouteImport.update({
  id: '/lojista',
  path: '/lojista',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarLicencaRoute = ComprarLicencaRouteImport.update({
  id: '/comprar-licenca',
  path: '/comprar-licenca',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorRoute = ComparadorRouteImport.update({
  id: '/comparador',
  path: '/comparador',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaborarRoute = ColaborarRouteImport.update({
  id: '/colaborar',
  path: '/colaborar',
  getParentRoute: () => rootRouteImport,
} as any)
const CestaBasicaRoute = CestaBasicaRouteImport.update({
  id: '/cesta-basica',
  path: '/cesta-basica',
  getParentRoute: () => rootRouteImport,
} as any)
const CestaRoute = CestaRouteImport.update({
  id: '/cesta',
  path: '/cesta',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoPublicoSlugRoute = ProdutoPublicoSlugRouteImport.update({
  id: '/produto-publico/$slug',
  path: '/produto-publico/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIdRoute = LojaIdRouteImport.update({
  id: '/loja/$id',
  path: '/loja/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoScansRoute = HistoricoScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => HistoricoRoute,
} as any)
const HistoricoProdutosRoute = HistoricoProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => HistoricoRoute,
} as any)
const HistoricoIdRoute = HistoricoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoricoRoute,
} as any)
const CotacaoIdRoute = CotacaoIdRouteImport.update({
  id: '/cotacao/$id',
  path: '/cotacao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprovanteIdRoute = ComprovanteIdRouteImport.update({
  id: '/comprovante/$id',
  path: '/comprovante/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CShareIdRoute = CShareIdRouteImport.update({
  id: '/c/$shareId',
  path: '/c/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSinonimosRoute = AdminSinonimosRouteImport.update({
  id: '/admin_/sinonimos',
  path: '/admin/sinonimos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin_/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRankCheckRoute = AdminRankCheckRouteImport.update({
  id: '/admin_/rank-check',
  path: '/admin/rank-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrecosRoute = AdminPrecosRouteImport.update({
  id: '/admin_/precos',
  path: '/admin/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMetricasRoute = AdminMetricasRouteImport.update({
  id: '/admin_/metricas',
  path: '/admin/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoteInserirRoute = AdminLoteInserirRouteImport.update({
  id: '/admin_/lote-inserir',
  path: '/admin/lote-inserir',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImageJobsRoute = AdminImageJobsRouteImport.update({
  id: '/admin_/image-jobs',
  path: '/admin/image-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIconesCategoriaRoute = AdminIconesCategoriaRouteImport.update({
  id: '/admin_/icones-categoria',
  path: '/admin/icones-categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCupomLoteRoute = AdminCupomLoteRouteImport.update({
  id: '/admin_/cupom-lote',
  path: '/admin/cupom-lote',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCupomRoute = AdminCupomRouteImport.update({
  id: '/admin_/cupom',
  path: '/admin/cupom',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsistenciaRoute = AdminConsistenciaRouteImport.update({
  id: '/admin_/consistencia',
  path: '/admin/consistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoberturaRoute = AdminCoberturaRouteImport.update({
  id: '/admin_/cobertura',
  path: '/admin/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogoRoute = AdminCatalogoRouteImport.update({
  id: '/admin_/catalogo',
  path: '/admin/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/admin_/auditoria',
  path: '/admin/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin_/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGestaoRoute = AdminGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminCatalogImageRoute = ApiAdminCatalogImageRouteImport.update({
  id: '/api/admin/catalog-image',
  path: '/api/admin/catalog-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoberturaIdRoute = AdminCoberturaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCoberturaRoute,
} as any)
const LojaIdProdutoSlugRoute = LojaIdProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => LojaIdRoute,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago/webhook',
    path: '/api/public/mercadopago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshCatalogImagesRoute =
  ApiPublicHooksRefreshCatalogImagesRouteImport.update({
    id: '/api/public/hooks/refresh-catalog-images',
    path: '/api/public/hooks/refresh-catalog-images',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDrainCatalogImagesRoute =
  ApiPublicHooksDrainCatalogImagesRouteImport.update({
    id: '/api/public/hooks/drain-catalog-images',
    path: '/api/public/hooks/drain-catalog-images',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCollabInboundRoute =
  ApiPublicHooksCollabInboundRouteImport.update({
    id: '/api/public/hooks/collab-inbound',
    path: '/api/public/hooks/collab-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRoute
  '/assinar': typeof AssinarRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/cesta': typeof CestaRoute
  '/cesta-basica': typeof CestaBasicaRoute
  '/colaborar': typeof ColaborarRoute
  '/comparador': typeof ComparadorRoute
  '/comparar': typeof CompararRoute
  '/comprar-licenca': typeof ComprarLicencaRoute
  '/financas': typeof FinancasRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/lojista': typeof LojistaRoute
  '/mapa': typeof MapaRoute
  '/melhores-precos': typeof MelhoresPrecosRoute
  '/minhas-licencas': typeof MinhasLicencasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-pin': typeof RecuperarPinRoute
  '/resgatar': typeof ResgatarRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/admin/gestao': typeof AdminGestaoRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/cobertura': typeof AdminCoberturaRouteWithChildren
  '/admin/consistencia': typeof AdminConsistenciaRoute
  '/admin/cupom': typeof AdminCupomRoute
  '/admin/cupom-lote': typeof AdminCupomLoteRoute
  '/admin/icones-categoria': typeof AdminIconesCategoriaRoute
  '/admin/image-jobs': typeof AdminImageJobsRoute
  '/admin/lote-inserir': typeof AdminLoteInserirRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/rank-check': typeof AdminRankCheckRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sinonimos': typeof AdminSinonimosRoute
  '/c/$shareId': typeof CShareIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/comprovante/$id': typeof ComprovanteIdRoute
  '/cotacao/$id': typeof CotacaoIdRoute
  '/historico/$id': typeof HistoricoIdRoute
  '/historico/produtos': typeof HistoricoProdutosRoute
  '/historico/scans': typeof HistoricoScansRoute
  '/loja/$id': typeof LojaIdRouteWithChildren
  '/produto-publico/$slug': typeof ProdutoPublicoSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/cobertura/$id': typeof AdminCoberturaIdRoute
  '/api/admin/catalog-image': typeof ApiAdminCatalogImageRoute
  '/api/public/hooks/collab-inbound': typeof ApiPublicHooksCollabInboundRoute
  '/api/public/hooks/drain-catalog-images': typeof ApiPublicHooksDrainCatalogImagesRoute
  '/api/public/hooks/refresh-catalog-images': typeof ApiPublicHooksRefreshCatalogImagesRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/loja/$id/produto/$slug': typeof LojaIdProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRoute
  '/assinar': typeof AssinarRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/cesta': typeof CestaRoute
  '/cesta-basica': typeof CestaBasicaRoute
  '/colaborar': typeof ColaborarRoute
  '/comparador': typeof ComparadorRoute
  '/comparar': typeof CompararRoute
  '/comprar-licenca': typeof ComprarLicencaRoute
  '/financas': typeof FinancasRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/lojista': typeof LojistaRoute
  '/mapa': typeof MapaRoute
  '/melhores-precos': typeof MelhoresPrecosRoute
  '/minhas-licencas': typeof MinhasLicencasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-pin': typeof RecuperarPinRoute
  '/resgatar': typeof ResgatarRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/admin/gestao': typeof AdminGestaoRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/cobertura': typeof AdminCoberturaRouteWithChildren
  '/admin/consistencia': typeof AdminConsistenciaRoute
  '/admin/cupom': typeof AdminCupomRoute
  '/admin/cupom-lote': typeof AdminCupomLoteRoute
  '/admin/icones-categoria': typeof AdminIconesCategoriaRoute
  '/admin/image-jobs': typeof AdminImageJobsRoute
  '/admin/lote-inserir': typeof AdminLoteInserirRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/rank-check': typeof AdminRankCheckRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sinonimos': typeof AdminSinonimosRoute
  '/c/$shareId': typeof CShareIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/comprovante/$id': typeof ComprovanteIdRoute
  '/cotacao/$id': typeof CotacaoIdRoute
  '/historico/$id': typeof HistoricoIdRoute
  '/historico/produtos': typeof HistoricoProdutosRoute
  '/historico/scans': typeof HistoricoScansRoute
  '/loja/$id': typeof LojaIdRouteWithChildren
  '/produto-publico/$slug': typeof ProdutoPublicoSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/cobertura/$id': typeof AdminCoberturaIdRoute
  '/api/admin/catalog-image': typeof ApiAdminCatalogImageRoute
  '/api/public/hooks/collab-inbound': typeof ApiPublicHooksCollabInboundRoute
  '/api/public/hooks/drain-catalog-images': typeof ApiPublicHooksDrainCatalogImagesRoute
  '/api/public/hooks/refresh-catalog-images': typeof ApiPublicHooksRefreshCatalogImagesRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/loja/$id/produto/$slug': typeof LojaIdProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRoute
  '/assinar': typeof AssinarRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/cesta': typeof CestaRoute
  '/cesta-basica': typeof CestaBasicaRoute
  '/colaborar': typeof ColaborarRoute
  '/comparador': typeof ComparadorRoute
  '/comparar': typeof CompararRoute
  '/comprar-licenca': typeof ComprarLicencaRoute
  '/financas': typeof FinancasRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/lojista': typeof LojistaRoute
  '/mapa': typeof MapaRoute
  '/melhores-precos': typeof MelhoresPrecosRoute
  '/minhas-licencas': typeof MinhasLicencasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-pin': typeof RecuperarPinRoute
  '/resgatar': typeof ResgatarRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/admin/gestao': typeof AdminGestaoRoute
  '/admin_/analytics': typeof AdminAnalyticsRoute
  '/admin_/auditoria': typeof AdminAuditoriaRoute
  '/admin_/catalogo': typeof AdminCatalogoRoute
  '/admin_/cobertura': typeof AdminCoberturaRouteWithChildren
  '/admin_/consistencia': typeof AdminConsistenciaRoute
  '/admin_/cupom': typeof AdminCupomRoute
  '/admin_/cupom-lote': typeof AdminCupomLoteRoute
  '/admin_/icones-categoria': typeof AdminIconesCategoriaRoute
  '/admin_/image-jobs': typeof AdminImageJobsRoute
  '/admin_/lote-inserir': typeof AdminLoteInserirRoute
  '/admin_/metricas': typeof AdminMetricasRoute
  '/admin_/precos': typeof AdminPrecosRoute
  '/admin_/rank-check': typeof AdminRankCheckRoute
  '/admin_/reports': typeof AdminReportsRoute
  '/admin_/sinonimos': typeof AdminSinonimosRoute
  '/c/$shareId': typeof CShareIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/comprovante/$id': typeof ComprovanteIdRoute
  '/cotacao/$id': typeof CotacaoIdRoute
  '/historico/$id': typeof HistoricoIdRoute
  '/historico/produtos': typeof HistoricoProdutosRoute
  '/historico/scans': typeof HistoricoScansRoute
  '/loja/$id': typeof LojaIdRouteWithChildren
  '/produto-publico/$slug': typeof ProdutoPublicoSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin_/cobertura/$id': typeof AdminCoberturaIdRoute
  '/api/admin/catalog-image': typeof ApiAdminCatalogImageRoute
  '/api/public/hooks/collab-inbound': typeof ApiPublicHooksCollabInboundRoute
  '/api/public/hooks/drain-catalog-images': typeof ApiPublicHooksDrainCatalogImagesRoute
  '/api/public/hooks/refresh-catalog-images': typeof ApiPublicHooksRefreshCatalogImagesRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/loja/$id/produto/$slug': typeof LojaIdProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/alertas'
    | '/app'
    | '/assinar'
    | '/assinatura'
    | '/auth'
    | '/buscar'
    | '/cadastro'
    | '/cesta'
    | '/cesta-basica'
    | '/colaborar'
    | '/comparador'
    | '/comparar'
    | '/comprar-licenca'
    | '/financas'
    | '/historico'
    | '/lista'
    | '/login'
    | '/lojista'
    | '/mapa'
    | '/melhores-precos'
    | '/minhas-licencas'
    | '/notificacoes'
    | '/onboarding'
    | '/perfil'
    | '/planos'
    | '/precos'
    | '/privacidade'
    | '/recuperar-pin'
    | '/resgatar'
    | '/sem-permissao'
    | '/admin/gestao'
    | '/admin/analytics'
    | '/admin/auditoria'
    | '/admin/catalogo'
    | '/admin/cobertura'
    | '/admin/consistencia'
    | '/admin/cupom'
    | '/admin/cupom-lote'
    | '/admin/icones-categoria'
    | '/admin/image-jobs'
    | '/admin/lote-inserir'
    | '/admin/metricas'
    | '/admin/precos'
    | '/admin/rank-check'
    | '/admin/reports'
    | '/admin/sinonimos'
    | '/c/$shareId'
    | '/checkout/$id'
    | '/comprovante/$id'
    | '/cotacao/$id'
    | '/historico/$id'
    | '/historico/produtos'
    | '/historico/scans'
    | '/loja/$id'
    | '/produto-publico/$slug'
    | '/produto/$id'
    | '/admin/cobertura/$id'
    | '/api/admin/catalog-image'
    | '/api/public/hooks/collab-inbound'
    | '/api/public/hooks/drain-catalog-images'
    | '/api/public/hooks/refresh-catalog-images'
    | '/api/public/mercadopago/webhook'
    | '/loja/$id/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/alertas'
    | '/app'
    | '/assinar'
    | '/assinatura'
    | '/auth'
    | '/buscar'
    | '/cadastro'
    | '/cesta'
    | '/cesta-basica'
    | '/colaborar'
    | '/comparador'
    | '/comparar'
    | '/comprar-licenca'
    | '/financas'
    | '/historico'
    | '/lista'
    | '/login'
    | '/lojista'
    | '/mapa'
    | '/melhores-precos'
    | '/minhas-licencas'
    | '/notificacoes'
    | '/onboarding'
    | '/perfil'
    | '/planos'
    | '/precos'
    | '/privacidade'
    | '/recuperar-pin'
    | '/resgatar'
    | '/sem-permissao'
    | '/admin/gestao'
    | '/admin/analytics'
    | '/admin/auditoria'
    | '/admin/catalogo'
    | '/admin/cobertura'
    | '/admin/consistencia'
    | '/admin/cupom'
    | '/admin/cupom-lote'
    | '/admin/icones-categoria'
    | '/admin/image-jobs'
    | '/admin/lote-inserir'
    | '/admin/metricas'
    | '/admin/precos'
    | '/admin/rank-check'
    | '/admin/reports'
    | '/admin/sinonimos'
    | '/c/$shareId'
    | '/checkout/$id'
    | '/comprovante/$id'
    | '/cotacao/$id'
    | '/historico/$id'
    | '/historico/produtos'
    | '/historico/scans'
    | '/loja/$id'
    | '/produto-publico/$slug'
    | '/produto/$id'
    | '/admin/cobertura/$id'
    | '/api/admin/catalog-image'
    | '/api/public/hooks/collab-inbound'
    | '/api/public/hooks/drain-catalog-images'
    | '/api/public/hooks/refresh-catalog-images'
    | '/api/public/mercadopago/webhook'
    | '/loja/$id/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/alertas'
    | '/app'
    | '/assinar'
    | '/assinatura'
    | '/auth'
    | '/buscar'
    | '/cadastro'
    | '/cesta'
    | '/cesta-basica'
    | '/colaborar'
    | '/comparador'
    | '/comparar'
    | '/comprar-licenca'
    | '/financas'
    | '/historico'
    | '/lista'
    | '/login'
    | '/lojista'
    | '/mapa'
    | '/melhores-precos'
    | '/minhas-licencas'
    | '/notificacoes'
    | '/onboarding'
    | '/perfil'
    | '/planos'
    | '/precos'
    | '/privacidade'
    | '/recuperar-pin'
    | '/resgatar'
    | '/sem-permissao'
    | '/admin/gestao'
    | '/admin_/analytics'
    | '/admin_/auditoria'
    | '/admin_/catalogo'
    | '/admin_/cobertura'
    | '/admin_/consistencia'
    | '/admin_/cupom'
    | '/admin_/cupom-lote'
    | '/admin_/icones-categoria'
    | '/admin_/image-jobs'
    | '/admin_/lote-inserir'
    | '/admin_/metricas'
    | '/admin_/precos'
    | '/admin_/rank-check'
    | '/admin_/reports'
    | '/admin_/sinonimos'
    | '/c/$shareId'
    | '/checkout/$id'
    | '/comprovante/$id'
    | '/cotacao/$id'
    | '/historico/$id'
    | '/historico/produtos'
    | '/historico/scans'
    | '/loja/$id'
    | '/produto-publico/$slug'
    | '/produto/$id'
    | '/admin_/cobertura/$id'
    | '/api/admin/catalog-image'
    | '/api/public/hooks/collab-inbound'
    | '/api/public/hooks/drain-catalog-images'
    | '/api/public/hooks/refresh-catalog-images'
    | '/api/public/mercadopago/webhook'
    | '/loja/$id/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AlertasRoute: typeof AlertasRoute
  AppRoute: typeof AppRoute
  AssinarRoute: typeof AssinarRoute
  AssinaturaRoute: typeof AssinaturaRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  CadastroRoute: typeof CadastroRoute
  CestaRoute: typeof CestaRoute
  CestaBasicaRoute: typeof CestaBasicaRoute
  ColaborarRoute: typeof ColaborarRoute
  ComparadorRoute: typeof ComparadorRoute
  CompararRoute: typeof CompararRoute
  ComprarLicencaRoute: typeof ComprarLicencaRoute
  FinancasRoute: typeof FinancasRoute
  HistoricoRoute: typeof HistoricoRouteWithChildren
  ListaRoute: typeof ListaRoute
  LoginRoute: typeof LoginRoute
  LojistaRoute: typeof LojistaRoute
  MapaRoute: typeof MapaRoute
  MelhoresPrecosRoute: typeof MelhoresPrecosRoute
  MinhasLicencasRoute: typeof MinhasLicencasRoute
  NotificacoesRoute: typeof NotificacoesRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  PlanosRoute: typeof PlanosRoute
  PrecosRoute: typeof PrecosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarPinRoute: typeof RecuperarPinRoute
  ResgatarRoute: typeof ResgatarRoute
  SemPermissaoRoute: typeof SemPermissaoRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminCatalogoRoute: typeof AdminCatalogoRoute
  AdminCoberturaRoute: typeof AdminCoberturaRouteWithChildren
  AdminConsistenciaRoute: typeof AdminConsistenciaRoute
  AdminCupomRoute: typeof AdminCupomRoute
  AdminCupomLoteRoute: typeof AdminCupomLoteRoute
  AdminIconesCategoriaRoute: typeof AdminIconesCategoriaRoute
  AdminImageJobsRoute: typeof AdminImageJobsRoute
  AdminLoteInserirRoute: typeof AdminLoteInserirRoute
  AdminMetricasRoute: typeof AdminMetricasRoute
  AdminPrecosRoute: typeof AdminPrecosRoute
  AdminRankCheckRoute: typeof AdminRankCheckRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSinonimosRoute: typeof AdminSinonimosRoute
  CShareIdRoute: typeof CShareIdRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  ComprovanteIdRoute: typeof ComprovanteIdRoute
  CotacaoIdRoute: typeof CotacaoIdRoute
  LojaIdRoute: typeof LojaIdRouteWithChildren
  ProdutoPublicoSlugRoute: typeof ProdutoPublicoSlugRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  ApiAdminCatalogImageRoute: typeof ApiAdminCatalogImageRoute
  ApiPublicHooksCollabInboundRoute: typeof ApiPublicHooksCollabInboundRoute
  ApiPublicHooksDrainCatalogImagesRoute: typeof ApiPublicHooksDrainCatalogImagesRoute
  ApiPublicHooksRefreshCatalogImagesRoute: typeof ApiPublicHooksRefreshCatalogImagesRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sem-permissao': {
      id: '/sem-permissao'
      path: '/sem-permissao'
      fullPath: '/sem-permissao'
      preLoaderRoute: typeof SemPermissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resgatar': {
      id: '/resgatar'
      path: '/resgatar'
      fullPath: '/resgatar'
      preLoaderRoute: typeof ResgatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-pin': {
      id: '/recuperar-pin'
      path: '/recuperar-pin'
      fullPath: '/recuperar-pin'
      preLoaderRoute: typeof RecuperarPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-licencas': {
      id: '/minhas-licencas'
      path: '/minhas-licencas'
      fullPath: '/minhas-licencas'
      preLoaderRoute: typeof MinhasLicencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melhores-precos': {
      id: '/melhores-precos'
      path: '/melhores-precos'
      fullPath: '/melhores-precos'
      preLoaderRoute: typeof MelhoresPrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojista': {
      id: '/lojista'
      path: '/lojista'
      fullPath: '/lojista'
      preLoaderRoute: typeof LojistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar-licenca': {
      id: '/comprar-licenca'
      path: '/comprar-licenca'
      fullPath: '/comprar-licenca'
      preLoaderRoute: typeof ComprarLicencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador': {
      id: '/comparador'
      path: '/comparador'
      fullPath: '/comparador'
      preLoaderRoute: typeof ComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborar': {
      id: '/colaborar'
      path: '/colaborar'
      fullPath: '/colaborar'
      preLoaderRoute: typeof ColaborarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cesta-basica': {
      id: '/cesta-basica'
      path: '/cesta-basica'
      fullPath: '/cesta-basica'
      preLoaderRoute: typeof CestaBasicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cesta': {
      id: '/cesta'
      path: '/cesta'
      fullPath: '/cesta'
      preLoaderRoute: typeof CestaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto-publico/$slug': {
      id: '/produto-publico/$slug'
      path: '/produto-publico/$slug'
      fullPath: '/produto-publico/$slug'
      preLoaderRoute: typeof ProdutoPublicoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$id': {
      id: '/loja/$id'
      path: '/loja/$id'
      fullPath: '/loja/$id'
      preLoaderRoute: typeof LojaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/scans': {
      id: '/historico/scans'
      path: '/scans'
      fullPath: '/historico/scans'
      preLoaderRoute: typeof HistoricoScansRouteImport
      parentRoute: typeof HistoricoRoute
    }
    '/historico/produtos': {
      id: '/historico/produtos'
      path: '/produtos'
      fullPath: '/historico/produtos'
      preLoaderRoute: typeof HistoricoProdutosRouteImport
      parentRoute: typeof HistoricoRoute
    }
    '/historico/$id': {
      id: '/historico/$id'
      path: '/$id'
      fullPath: '/historico/$id'
      preLoaderRoute: typeof HistoricoIdRouteImport
      parentRoute: typeof HistoricoRoute
    }
    '/cotacao/$id': {
      id: '/cotacao/$id'
      path: '/cotacao/$id'
      fullPath: '/cotacao/$id'
      preLoaderRoute: typeof CotacaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprovante/$id': {
      id: '/comprovante/$id'
      path: '/comprovante/$id'
      fullPath: '/comprovante/$id'
      preLoaderRoute: typeof ComprovanteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$shareId': {
      id: '/c/$shareId'
      path: '/c/$shareId'
      fullPath: '/c/$shareId'
      preLoaderRoute: typeof CShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/sinonimos': {
      id: '/admin_/sinonimos'
      path: '/admin/sinonimos'
      fullPath: '/admin/sinonimos'
      preLoaderRoute: typeof AdminSinonimosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reports': {
      id: '/admin_/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/rank-check': {
      id: '/admin_/rank-check'
      path: '/admin/rank-check'
      fullPath: '/admin/rank-check'
      preLoaderRoute: typeof AdminRankCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/precos': {
      id: '/admin_/precos'
      path: '/admin/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AdminPrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/metricas': {
      id: '/admin_/metricas'
      path: '/admin/metricas'
      fullPath: '/admin/metricas'
      preLoaderRoute: typeof AdminMetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/lote-inserir': {
      id: '/admin_/lote-inserir'
      path: '/admin/lote-inserir'
      fullPath: '/admin/lote-inserir'
      preLoaderRoute: typeof AdminLoteInserirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/image-jobs': {
      id: '/admin_/image-jobs'
      path: '/admin/image-jobs'
      fullPath: '/admin/image-jobs'
      preLoaderRoute: typeof AdminImageJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/icones-categoria': {
      id: '/admin_/icones-categoria'
      path: '/admin/icones-categoria'
      fullPath: '/admin/icones-categoria'
      preLoaderRoute: typeof AdminIconesCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cupom-lote': {
      id: '/admin_/cupom-lote'
      path: '/admin/cupom-lote'
      fullPath: '/admin/cupom-lote'
      preLoaderRoute: typeof AdminCupomLoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cupom': {
      id: '/admin_/cupom'
      path: '/admin/cupom'
      fullPath: '/admin/cupom'
      preLoaderRoute: typeof AdminCupomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/consistencia': {
      id: '/admin_/consistencia'
      path: '/admin/consistencia'
      fullPath: '/admin/consistencia'
      preLoaderRoute: typeof AdminConsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cobertura': {
      id: '/admin_/cobertura'
      path: '/admin/cobertura'
      fullPath: '/admin/cobertura'
      preLoaderRoute: typeof AdminCoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/catalogo': {
      id: '/admin_/catalogo'
      path: '/admin/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AdminCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/auditoria': {
      id: '/admin_/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/analytics': {
      id: '/admin_/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gestao': {
      id: '/admin/gestao'
      path: '/gestao'
      fullPath: '/admin/gestao'
      preLoaderRoute: typeof AdminGestaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/catalog-image': {
      id: '/api/admin/catalog-image'
      path: '/api/admin/catalog-image'
      fullPath: '/api/admin/catalog-image'
      preLoaderRoute: typeof ApiAdminCatalogImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cobertura/$id': {
      id: '/admin_/cobertura/$id'
      path: '/$id'
      fullPath: '/admin/cobertura/$id'
      preLoaderRoute: typeof AdminCoberturaIdRouteImport
      parentRoute: typeof AdminCoberturaRoute
    }
    '/loja/$id/produto/$slug': {
      id: '/loja/$id/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/loja/$id/produto/$slug'
      preLoaderRoute: typeof LojaIdProdutoSlugRouteImport
      parentRoute: typeof LojaIdRoute
    }
    '/api/public/mercadopago/webhook': {
      id: '/api/public/mercadopago/webhook'
      path: '/api/public/mercadopago/webhook'
      fullPath: '/api/public/mercadopago/webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-catalog-images': {
      id: '/api/public/hooks/refresh-catalog-images'
      path: '/api/public/hooks/refresh-catalog-images'
      fullPath: '/api/public/hooks/refresh-catalog-images'
      preLoaderRoute: typeof ApiPublicHooksRefreshCatalogImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/drain-catalog-images': {
      id: '/api/public/hooks/drain-catalog-images'
      path: '/api/public/hooks/drain-catalog-images'
      fullPath: '/api/public/hooks/drain-catalog-images'
      preLoaderRoute: typeof ApiPublicHooksDrainCatalogImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/collab-inbound': {
      id: '/api/public/hooks/collab-inbound'
      path: '/api/public/hooks/collab-inbound'
      fullPath: '/api/public/hooks/collab-inbound'
      preLoaderRoute: typeof ApiPublicHooksCollabInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminGestaoRoute: typeof AdminGestaoRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGestaoRoute: AdminGestaoRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HistoricoRouteChildren {
  HistoricoIdRoute: typeof HistoricoIdRoute
  HistoricoProdutosRoute: typeof HistoricoProdutosRoute
  HistoricoScansRoute: typeof HistoricoScansRoute
}

const HistoricoRouteChildren: HistoricoRouteChildren = {
  HistoricoIdRoute: HistoricoIdRoute,
  HistoricoProdutosRoute: HistoricoProdutosRoute,
  HistoricoScansRoute: HistoricoScansRoute,
}

const HistoricoRouteWithChildren = HistoricoRoute._addFileChildren(
  HistoricoRouteChildren,
)

interface AdminCoberturaRouteChildren {
  AdminCoberturaIdRoute: typeof AdminCoberturaIdRoute
}

const AdminCoberturaRouteChildren: AdminCoberturaRouteChildren = {
  AdminCoberturaIdRoute: AdminCoberturaIdRoute,
}

const AdminCoberturaRouteWithChildren = AdminCoberturaRoute._addFileChildren(
  AdminCoberturaRouteChildren,
)

interface LojaIdRouteChildren {
  LojaIdProdutoSlugRoute: typeof LojaIdProdutoSlugRoute
}

const LojaIdRouteChildren: LojaIdRouteChildren = {
  LojaIdProdutoSlugRoute: LojaIdProdutoSlugRoute,
}

const LojaIdRouteWithChildren =
  LojaIdRoute._addFileChildren(LojaIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AlertasRoute: AlertasRoute,
  AppRoute: AppRoute,
  AssinarRoute: AssinarRoute,
  AssinaturaRoute: AssinaturaRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  CadastroRoute: CadastroRoute,
  CestaRoute: CestaRoute,
  CestaBasicaRoute: CestaBasicaRoute,
  ColaborarRoute: ColaborarRoute,
  ComparadorRoute: ComparadorRoute,
  CompararRoute: CompararRoute,
  ComprarLicencaRoute: ComprarLicencaRoute,
  FinancasRoute: FinancasRoute,
  HistoricoRoute: HistoricoRouteWithChildren,
  ListaRoute: ListaRoute,
  LoginRoute: LoginRoute,
  LojistaRoute: LojistaRoute,
  MapaRoute: MapaRoute,
  MelhoresPrecosRoute: MelhoresPrecosRoute,
  MinhasLicencasRoute: MinhasLicencasRoute,
  NotificacoesRoute: NotificacoesRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  PlanosRoute: PlanosRoute,
  PrecosRoute: PrecosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarPinRoute: RecuperarPinRoute,
  ResgatarRoute: ResgatarRoute,
  SemPermissaoRoute: SemPermissaoRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminCatalogoRoute: AdminCatalogoRoute,
  AdminCoberturaRoute: AdminCoberturaRouteWithChildren,
  AdminConsistenciaRoute: AdminConsistenciaRoute,
  AdminCupomRoute: AdminCupomRoute,
  AdminCupomLoteRoute: AdminCupomLoteRoute,
  AdminIconesCategoriaRoute: AdminIconesCategoriaRoute,
  AdminImageJobsRoute: AdminImageJobsRoute,
  AdminLoteInserirRoute: AdminLoteInserirRoute,
  AdminMetricasRoute: AdminMetricasRoute,
  AdminPrecosRoute: AdminPrecosRoute,
  AdminRankCheckRoute: AdminRankCheckRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSinonimosRoute: AdminSinonimosRoute,
  CShareIdRoute: CShareIdRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  ComprovanteIdRoute: ComprovanteIdRoute,
  CotacaoIdRoute: CotacaoIdRoute,
  LojaIdRoute: LojaIdRouteWithChildren,
  ProdutoPublicoSlugRoute: ProdutoPublicoSlugRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  ApiAdminCatalogImageRoute: ApiAdminCatalogImageRoute,
  ApiPublicHooksCollabInboundRoute: ApiPublicHooksCollabInboundRoute,
  ApiPublicHooksDrainCatalogImagesRoute: ApiPublicHooksDrainCatalogImagesRoute,
  ApiPublicHooksRefreshCatalogImagesRoute:
    ApiPublicHooksRefreshCatalogImagesRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
