/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendenciasRouteImport } from './routes/tendencias'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SemPermissaoRouteImport } from './routes/sem-permissao'
import { Route as ResgatarRouteImport } from './routes/resgatar'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrecosPorCategoriaRouteImport } from './routes/precos-por-categoria'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OndeComprarRouteImport } from './routes/onde-comprar'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as MinhasLicencasRouteImport } from './routes/minhas-licencas'
import { Route as MinhaIaRouteImport } from './routes/minha-ia'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as MelhoresPrecosRouteImport } from './routes/melhores-precos'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LojistaRouteImport } from './routes/lojista'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as FarmaciasRouteImport } from './routes/farmacias'
import { Route as FaleConoscoRouteImport } from './routes/fale-conosco'
import { Route as EstabelecimentosRouteImport } from './routes/estabelecimentos'
import { Route as EconomiaRouteImport } from './routes/economia'
import { Route as ComprarLicencaRouteImport } from './routes/comprar-licenca'
import { Route as ComparadorAoVivoRouteImport } from './routes/comparador-ao-vivo'
import { Route as ComparadorRouteImport } from './routes/comparador'
import { Route as ColaborarRouteImport } from './routes/colaborar'
import { Route as CestaBasicaRouteImport } from './routes/cesta-basica'
import { Route as CestaRouteImport } from './routes/cesta'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as AppRouteImport } from './routes/app'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as ProdutoPublicoSlugRouteImport } from './routes/produto-publico.$slug'
import { Route as OndeComprarProdutoRouteImport } from './routes/onde-comprar_.$produto'
import { Route as LojaIdRouteImport } from './routes/loja.$id'
import { Route as ListaProntaRouteImport } from './routes/lista_.pronta'
import { Route as ListaNovaRouteImport } from './routes/lista_.nova'
import { Route as HistoricoScansRouteImport } from './routes/historico.scans'
import { Route as HistoricoProdutosRouteImport } from './routes/historico.produtos'
import { Route as HistoricoIdRouteImport } from './routes/historico.$id'
import { Route as EstabelecimentoSlugRouteImport } from './routes/estabelecimento.$slug'
import { Route as CotacaoIdRouteImport } from './routes/cotacao.$id'
import { Route as ComprovanteIdRouteImport } from './routes/comprovante.$id'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as CatalogoSlugRouteImport } from './routes/catalogo.$slug'
import { Route as CShareIdRouteImport } from './routes/c.$shareId'
import { Route as AdminWebhooksRouteImport } from './routes/admin_.webhooks'
import { Route as AdminVitrineRouteImport } from './routes/admin_.vitrine'
import { Route as AdminSinonimosRouteImport } from './routes/admin_.sinonimos'
import { Route as AdminReportsRouteImport } from './routes/admin_.reports'
import { Route as AdminRankCheckRouteImport } from './routes/admin_.rank-check'
import { Route as AdminPromocoesCodigosRouteImport } from './routes/admin_.promocoes-codigos'
import { Route as AdminPromocoesRouteImport } from './routes/admin_.promocoes'
import { Route as AdminPrecosRouteImport } from './routes/admin_.precos'
import { Route as AdminPrecoRapidoRouteImport } from './routes/admin_.preco-rapido'
import { Route as AdminOperacaoRouteImport } from './routes/admin_.operacao'
import { Route as AdminMetricasRouteImport } from './routes/admin_.metricas'
import { Route as AdminLoteInserirRouteImport } from './routes/admin_.lote-inserir'
import { Route as AdminImportacoesRouteImport } from './routes/admin_.importacoes'
import { Route as AdminImageJobsRouteImport } from './routes/admin_.image-jobs'
import { Route as AdminIconesCategoriaRouteImport } from './routes/admin_.icones-categoria'
import { Route as AdminIaRouteImport } from './routes/admin_.ia'
import { Route as AdminHistoricoPrecosRouteImport } from './routes/admin_.historico-precos'
import { Route as AdminCupomLoteRouteImport } from './routes/admin_.cupom-lote'
import { Route as AdminCupomRouteImport } from './routes/admin_.cupom'
import { Route as AdminConversoesRouteImport } from './routes/admin_.conversoes'
import { Route as AdminContasRouteImport } from './routes/admin_.contas'
import { Route as AdminConsistenciaRouteImport } from './routes/admin_.consistencia'
import { Route as AdminCoberturaRouteImport } from './routes/admin_.cobertura'
import { Route as AdminClientesRouteImport } from './routes/admin_.clientes'
import { Route as AdminCestaAuditoriaRouteImport } from './routes/admin_.cesta-auditoria'
import { Route as AdminCestaRouteImport } from './routes/admin_.cesta'
import { Route as AdminCategorizacaoRouteImport } from './routes/admin_.categorizacao'
import { Route as AdminCatalogoRouteImport } from './routes/admin_.catalogo'
import { Route as AdminCadastroFotoRouteImport } from './routes/admin_.cadastro-foto'
import { Route as AdminAuditoriaNumerosRouteImport } from './routes/admin_.auditoria-numeros'
import { Route as AdminAuditoriaAcessosRouteImport } from './routes/admin_.auditoria-acessos'
import { Route as AdminAuditoriaRouteImport } from './routes/admin_.auditoria'
import { Route as AdminAnalyticsRouteImport } from './routes/admin_.analytics'
import { Route as AdminAcessosTemporariosRouteImport } from './routes/admin_.acessos-temporarios'
import { Route as AdminGestaoRouteImport } from './routes/admin.gestao'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'
import { Route as ApiAdminCatalogImageRouteImport } from './routes/api/admin/catalog-image'
import { Route as AdminCoberturaIdRouteImport } from './routes/admin_.cobertura.$id'
import { Route as LojaIdProdutoSlugRouteImport } from './routes/loja.$id.produto.$slug'
import { Route as EstabelecimentoSlugCategoriaCategoryRouteImport } from './routes/estabelecimento.$slug.categoria.$category'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago/webhook'
import { Route as ApiPublicHooksRetryActivationEmailsRouteImport } from './routes/api/public/hooks/retry-activation-emails'
import { Route as ApiPublicHooksRefreshCatalogImagesRouteImport } from './routes/api/public/hooks/refresh-catalog-images'
import { Route as ApiPublicHooksDrainCatalogImagesRouteImport } from './routes/api/public/hooks/drain-catalog-images'
import { Route as ApiPublicHooksCollabInboundRouteImport } from './routes/api/public/hooks/collab-inbound'

const TendenciasRoute = TendenciasRouteImport.update({
  id: '/tendencias',
  path: '/tendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SemPermissaoRoute = SemPermissaoRouteImport.update({
  id: '/sem-permissao',
  path: '/sem-permissao',
  getParentRoute: () => rootRouteImport,
} as any)
const ResgatarRoute = ResgatarRouteImport.update({
  id: '/resgatar',
  path: '/resgatar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosPorCategoriaRoute = PrecosPorCategoriaRouteImport.update({
  id: '/precos-por-categoria',
  path: '/precos-por-categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeComprarRoute = OndeComprarRouteImport.update({
  id: '/onde-comprar',
  path: '/onde-comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasLicencasRoute = MinhasLicencasRouteImport.update({
  id: '/minhas-licencas',
  path: '/minhas-licencas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaIaRoute = MinhaIaRouteImport.update({
  id: '/minha-ia',
  path: '/minha-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MelhoresPrecosRoute = MelhoresPrecosRouteImport.update({
  id: '/melhores-precos',
  path: '/melhores-precos',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LojistaRoute = LojistaRouteImport.update({
  id: '/lojista',
  path: '/lojista',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmaciasRoute = FarmaciasRouteImport.update({
  id: '/farmacias',
  path: '/farmacias',
  getParentRoute: () => rootRouteImport,
} as any)
const FaleConoscoRoute = FaleConoscoRouteImport.update({
  id: '/fale-conosco',
  path: '/fale-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const EstabelecimentosRoute = EstabelecimentosRouteImport.update({
  id: '/estabelecimentos',
  path: '/estabelecimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomiaRoute = EconomiaRouteImport.update({
  id: '/economia',
  path: '/economia',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarLicencaRoute = ComprarLicencaRouteImport.update({
  id: '/comprar-licenca',
  path: '/comprar-licenca',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorAoVivoRoute = ComparadorAoVivoRouteImport.update({
  id: '/comparador-ao-vivo',
  path: '/comparador-ao-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorRoute = ComparadorRouteImport.update({
  id: '/comparador',
  path: '/comparador',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaborarRoute = ColaborarRouteImport.update({
  id: '/colaborar',
  path: '/colaborar',
  getParentRoute: () => rootRouteImport,
} as any)
const CestaBasicaRoute = CestaBasicaRouteImport.update({
  id: '/cesta-basica',
  path: '/cesta-basica',
  getParentRoute: () => rootRouteImport,
} as any)
const CestaRoute = CestaRouteImport.update({
  id: '/cesta',
  path: '/cesta',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoPublicoSlugRoute = ProdutoPublicoSlugRouteImport.update({
  id: '/produto-publico/$slug',
  path: '/produto-publico/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeComprarProdutoRoute = OndeComprarProdutoRouteImport.update({
  id: '/onde-comprar_/$produto',
  path: '/onde-comprar/$produto',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIdRoute = LojaIdRouteImport.update({
  id: '/loja/$id',
  path: '/loja/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaProntaRoute = ListaProntaRouteImport.update({
  id: '/lista_/pronta',
  path: '/lista/pronta',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaNovaRoute = ListaNovaRouteImport.update({
  id: '/lista_/nova',
  path: '/lista/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoScansRoute = HistoricoScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => HistoricoRoute,
} as any)
const HistoricoProdutosRoute = HistoricoProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => HistoricoRoute,
} as any)
const HistoricoIdRoute = HistoricoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoricoRoute,
} as any)
const EstabelecimentoSlugRoute = EstabelecimentoSlugRouteImport.update({
  id: '/estabelecimento/$slug',
  path: '/estabelecimento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacaoIdRoute = CotacaoIdRouteImport.update({
  id: '/cotacao/$id',
  path: '/cotacao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprovanteIdRoute = ComprovanteIdRouteImport.update({
  id: '/comprovante/$id',
  path: '/comprovante/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoSlugRoute = CatalogoSlugRouteImport.update({
  id: '/catalogo/$slug',
  path: '/catalogo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CShareIdRoute = CShareIdRouteImport.update({
  id: '/c/$shareId',
  path: '/c/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/admin_/webhooks',
  path: '/admin/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVitrineRoute = AdminVitrineRouteImport.update({
  id: '/admin_/vitrine',
  path: '/admin/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSinonimosRoute = AdminSinonimosRouteImport.update({
  id: '/admin_/sinonimos',
  path: '/admin/sinonimos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin_/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRankCheckRoute = AdminRankCheckRouteImport.update({
  id: '/admin_/rank-check',
  path: '/admin/rank-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromocoesCodigosRoute = AdminPromocoesCodigosRouteImport.update({
  id: '/admin_/promocoes-codigos',
  path: '/admin/promocoes-codigos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromocoesRoute = AdminPromocoesRouteImport.update({
  id: '/admin_/promocoes',
  path: '/admin/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrecosRoute = AdminPrecosRouteImport.update({
  id: '/admin_/precos',
  path: '/admin/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrecoRapidoRoute = AdminPrecoRapidoRouteImport.update({
  id: '/admin_/preco-rapido',
  path: '/admin/preco-rapido',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperacaoRoute = AdminOperacaoRouteImport.update({
  id: '/admin_/operacao',
  path: '/admin/operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMetricasRoute = AdminMetricasRouteImport.update({
  id: '/admin_/metricas',
  path: '/admin/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoteInserirRoute = AdminLoteInserirRouteImport.update({
  id: '/admin_/lote-inserir',
  path: '/admin/lote-inserir',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportacoesRoute = AdminImportacoesRouteImport.update({
  id: '/admin_/importacoes',
  path: '/admin/importacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImageJobsRoute = AdminImageJobsRouteImport.update({
  id: '/admin_/image-jobs',
  path: '/admin/image-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIconesCategoriaRoute = AdminIconesCategoriaRouteImport.update({
  id: '/admin_/icones-categoria',
  path: '/admin/icones-categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIaRoute = AdminIaRouteImport.update({
  id: '/admin_/ia',
  path: '/admin/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoricoPrecosRoute = AdminHistoricoPrecosRouteImport.update({
  id: '/admin_/historico-precos',
  path: '/admin/historico-precos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCupomLoteRoute = AdminCupomLoteRouteImport.update({
  id: '/admin_/cupom-lote',
  path: '/admin/cupom-lote',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCupomRoute = AdminCupomRouteImport.update({
  id: '/admin_/cupom',
  path: '/admin/cupom',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConversoesRoute = AdminConversoesRouteImport.update({
  id: '/admin_/conversoes',
  path: '/admin/conversoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContasRoute = AdminContasRouteImport.update({
  id: '/admin_/contas',
  path: '/admin/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsistenciaRoute = AdminConsistenciaRouteImport.update({
  id: '/admin_/consistencia',
  path: '/admin/consistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoberturaRoute = AdminCoberturaRouteImport.update({
  id: '/admin_/cobertura',
  path: '/admin/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin_/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCestaAuditoriaRoute = AdminCestaAuditoriaRouteImport.update({
  id: '/admin_/cesta-auditoria',
  path: '/admin/cesta-auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCestaRoute = AdminCestaRouteImport.update({
  id: '/admin_/cesta',
  path: '/admin/cesta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategorizacaoRoute = AdminCategorizacaoRouteImport.update({
  id: '/admin_/categorizacao',
  path: '/admin/categorizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogoRoute = AdminCatalogoRouteImport.update({
  id: '/admin_/catalogo',
  path: '/admin/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCadastroFotoRoute = AdminCadastroFotoRouteImport.update({
  id: '/admin_/cadastro-foto',
  path: '/admin/cadastro-foto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditoriaNumerosRoute = AdminAuditoriaNumerosRouteImport.update({
  id: '/admin_/auditoria-numeros',
  path: '/admin/auditoria-numeros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditoriaAcessosRoute = AdminAuditoriaAcessosRouteImport.update({
  id: '/admin_/auditoria-acessos',
  path: '/admin/auditoria-acessos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/admin_/auditoria',
  path: '/admin/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin_/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcessosTemporariosRoute = AdminAcessosTemporariosRouteImport.update({
  id: '/admin_/acessos-temporarios',
  path: '/admin/acessos-temporarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGestaoRoute = AdminGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCatalogImageRoute = ApiAdminCatalogImageRouteImport.update({
  id: '/api/admin/catalog-image',
  path: '/api/admin/catalog-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoberturaIdRoute = AdminCoberturaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCoberturaRoute,
} as any)
const LojaIdProdutoSlugRoute = LojaIdProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => LojaIdRoute,
} as any)
const EstabelecimentoSlugCategoriaCategoryRoute =
  EstabelecimentoSlugCategoriaCategoryRouteImport.update({
    id: '/categoria/$category',
    path: '/categoria/$category',
    getParentRoute: () => EstabelecimentoSlugRoute,
  } as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago/webhook',
    path: '/api/public/mercadopago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRetryActivationEmailsRoute =
  ApiPublicHooksRetryActivationEmailsRouteImport.update({
    id: '/api/public/hooks/retry-activation-emails',
    path: '/api/public/hooks/retry-activation-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshCatalogImagesRoute =
  ApiPublicHooksRefreshCatalogImagesRouteImport.update({
    id: '/api/public/hooks/refresh-catalog-images',
    path: '/api/public/hooks/refresh-catalog-images',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDrainCatalogImagesRoute =
  ApiPublicHooksDrainCatalogImagesRouteImport.update({
    id: '/api/public/hooks/drain-catalog-images',
    path: '/api/public/hooks/drain-catalog-images',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCollabInboundRoute =
  ApiPublicHooksCollabInboundRouteImport.update({
    id: '/api/public/hooks/collab-inbound',
    path: '/api/public/hooks/collab-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRoute
  '/assinar': typeof AssinarRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/cesta': typeof CestaRoute
  '/cesta-basica': typeof CestaBasicaRoute
  '/colaborar': typeof ColaborarRoute
  '/comparador': typeof ComparadorRoute
  '/comparador-ao-vivo': typeof ComparadorAoVivoRoute
  '/comprar-licenca': typeof ComprarLicencaRoute
  '/economia': typeof EconomiaRoute
  '/estabelecimentos': typeof EstabelecimentosRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/farmacias': typeof FarmaciasRoute
  '/favoritos': typeof FavoritosRoute
  '/financas': typeof FinancasRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/lojista': typeof LojistaRoute
  '/mapa': typeof MapaRoute
  '/melhores-precos': typeof MelhoresPrecosRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/minha-ia': typeof MinhaIaRoute
  '/minhas-licencas': typeof MinhasLicencasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/onde-comprar': typeof OndeComprarRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/precos': typeof PrecosRoute
  '/precos-por-categoria': typeof PrecosPorCategoriaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/resgatar': typeof ResgatarRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tendencias': typeof TendenciasRoute
  '/admin/gestao': typeof AdminGestaoRoute
  '/admin/acessos-temporarios': typeof AdminAcessosTemporariosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/auditoria-acessos': typeof AdminAuditoriaAcessosRoute
  '/admin/auditoria-numeros': typeof AdminAuditoriaNumerosRoute
  '/admin/cadastro-foto': typeof AdminCadastroFotoRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/categorizacao': typeof AdminCategorizacaoRoute
  '/admin/cesta': typeof AdminCestaRoute
  '/admin/cesta-auditoria': typeof AdminCestaAuditoriaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/cobertura': typeof AdminCoberturaRouteWithChildren
  '/admin/consistencia': typeof AdminConsistenciaRoute
  '/admin/contas': typeof AdminContasRoute
  '/admin/conversoes': typeof AdminConversoesRoute
  '/admin/cupom': typeof AdminCupomRoute
  '/admin/cupom-lote': typeof AdminCupomLoteRoute
  '/admin/historico-precos': typeof AdminHistoricoPrecosRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/icones-categoria': typeof AdminIconesCategoriaRoute
  '/admin/image-jobs': typeof AdminImageJobsRoute
  '/admin/importacoes': typeof AdminImportacoesRoute
  '/admin/lote-inserir': typeof AdminLoteInserirRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/operacao': typeof AdminOperacaoRoute
  '/admin/preco-rapido': typeof AdminPrecoRapidoRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/promocoes-codigos': typeof AdminPromocoesCodigosRoute
  '/admin/rank-check': typeof AdminRankCheckRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sinonimos': typeof AdminSinonimosRoute
  '/admin/vitrine': typeof AdminVitrineRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/c/$shareId': typeof CShareIdRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/comprovante/$id': typeof ComprovanteIdRoute
  '/cotacao/$id': typeof CotacaoIdRoute
  '/estabelecimento/$slug': typeof EstabelecimentoSlugRouteWithChildren
  '/historico/$id': typeof HistoricoIdRoute
  '/historico/produtos': typeof HistoricoProdutosRoute
  '/historico/scans': typeof HistoricoScansRoute
  '/lista/nova': typeof ListaNovaRoute
  '/lista/pronta': typeof ListaProntaRoute
  '/loja/$id': typeof LojaIdRouteWithChildren
  '/onde-comprar/$produto': typeof OndeComprarProdutoRoute
  '/produto-publico/$slug': typeof ProdutoPublicoSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/cobertura/$id': typeof AdminCoberturaIdRoute
  '/api/admin/catalog-image': typeof ApiAdminCatalogImageRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/hooks/collab-inbound': typeof ApiPublicHooksCollabInboundRoute
  '/api/public/hooks/drain-catalog-images': typeof ApiPublicHooksDrainCatalogImagesRoute
  '/api/public/hooks/refresh-catalog-images': typeof ApiPublicHooksRefreshCatalogImagesRoute
  '/api/public/hooks/retry-activation-emails': typeof ApiPublicHooksRetryActivationEmailsRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/estabelecimento/$slug/categoria/$category': typeof EstabelecimentoSlugCategoriaCategoryRoute
  '/loja/$id/produto/$slug': typeof LojaIdProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRoute
  '/assinar': typeof AssinarRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/cesta': typeof CestaRoute
  '/cesta-basica': typeof CestaBasicaRoute
  '/colaborar': typeof ColaborarRoute
  '/comparador': typeof ComparadorRoute
  '/comparador-ao-vivo': typeof ComparadorAoVivoRoute
  '/comprar-licenca': typeof ComprarLicencaRoute
  '/economia': typeof EconomiaRoute
  '/estabelecimentos': typeof EstabelecimentosRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/farmacias': typeof FarmaciasRoute
  '/favoritos': typeof FavoritosRoute
  '/financas': typeof FinancasRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/lojista': typeof LojistaRoute
  '/mapa': typeof MapaRoute
  '/melhores-precos': typeof MelhoresPrecosRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/minha-ia': typeof MinhaIaRoute
  '/minhas-licencas': typeof MinhasLicencasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/onde-comprar': typeof OndeComprarRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/precos': typeof PrecosRoute
  '/precos-por-categoria': typeof PrecosPorCategoriaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/resgatar': typeof ResgatarRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tendencias': typeof TendenciasRoute
  '/admin/gestao': typeof AdminGestaoRoute
  '/admin/acessos-temporarios': typeof AdminAcessosTemporariosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/auditoria-acessos': typeof AdminAuditoriaAcessosRoute
  '/admin/auditoria-numeros': typeof AdminAuditoriaNumerosRoute
  '/admin/cadastro-foto': typeof AdminCadastroFotoRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/categorizacao': typeof AdminCategorizacaoRoute
  '/admin/cesta': typeof AdminCestaRoute
  '/admin/cesta-auditoria': typeof AdminCestaAuditoriaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/cobertura': typeof AdminCoberturaRouteWithChildren
  '/admin/consistencia': typeof AdminConsistenciaRoute
  '/admin/contas': typeof AdminContasRoute
  '/admin/conversoes': typeof AdminConversoesRoute
  '/admin/cupom': typeof AdminCupomRoute
  '/admin/cupom-lote': typeof AdminCupomLoteRoute
  '/admin/historico-precos': typeof AdminHistoricoPrecosRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/icones-categoria': typeof AdminIconesCategoriaRoute
  '/admin/image-jobs': typeof AdminImageJobsRoute
  '/admin/importacoes': typeof AdminImportacoesRoute
  '/admin/lote-inserir': typeof AdminLoteInserirRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/operacao': typeof AdminOperacaoRoute
  '/admin/preco-rapido': typeof AdminPrecoRapidoRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/promocoes-codigos': typeof AdminPromocoesCodigosRoute
  '/admin/rank-check': typeof AdminRankCheckRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sinonimos': typeof AdminSinonimosRoute
  '/admin/vitrine': typeof AdminVitrineRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/c/$shareId': typeof CShareIdRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/comprovante/$id': typeof ComprovanteIdRoute
  '/cotacao/$id': typeof CotacaoIdRoute
  '/estabelecimento/$slug': typeof EstabelecimentoSlugRouteWithChildren
  '/historico/$id': typeof HistoricoIdRoute
  '/historico/produtos': typeof HistoricoProdutosRoute
  '/historico/scans': typeof HistoricoScansRoute
  '/lista/nova': typeof ListaNovaRoute
  '/lista/pronta': typeof ListaProntaRoute
  '/loja/$id': typeof LojaIdRouteWithChildren
  '/onde-comprar/$produto': typeof OndeComprarProdutoRoute
  '/produto-publico/$slug': typeof ProdutoPublicoSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/cobertura/$id': typeof AdminCoberturaIdRoute
  '/api/admin/catalog-image': typeof ApiAdminCatalogImageRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/hooks/collab-inbound': typeof ApiPublicHooksCollabInboundRoute
  '/api/public/hooks/drain-catalog-images': typeof ApiPublicHooksDrainCatalogImagesRoute
  '/api/public/hooks/refresh-catalog-images': typeof ApiPublicHooksRefreshCatalogImagesRoute
  '/api/public/hooks/retry-activation-emails': typeof ApiPublicHooksRetryActivationEmailsRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/estabelecimento/$slug/categoria/$category': typeof EstabelecimentoSlugCategoriaCategoryRoute
  '/loja/$id/produto/$slug': typeof LojaIdProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/alertas': typeof AlertasRoute
  '/app': typeof AppRoute
  '/assinar': typeof AssinarRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/cesta': typeof CestaRoute
  '/cesta-basica': typeof CestaBasicaRoute
  '/colaborar': typeof ColaborarRoute
  '/comparador': typeof ComparadorRoute
  '/comparador-ao-vivo': typeof ComparadorAoVivoRoute
  '/comprar-licenca': typeof ComprarLicencaRoute
  '/economia': typeof EconomiaRoute
  '/estabelecimentos': typeof EstabelecimentosRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/farmacias': typeof FarmaciasRoute
  '/favoritos': typeof FavoritosRoute
  '/financas': typeof FinancasRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/lojista': typeof LojistaRoute
  '/mapa': typeof MapaRoute
  '/melhores-precos': typeof MelhoresPrecosRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/minha-ia': typeof MinhaIaRoute
  '/minhas-licencas': typeof MinhasLicencasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/onde-comprar': typeof OndeComprarRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/precos': typeof PrecosRoute
  '/precos-por-categoria': typeof PrecosPorCategoriaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/resgatar': typeof ResgatarRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tendencias': typeof TendenciasRoute
  '/admin/gestao': typeof AdminGestaoRoute
  '/admin_/acessos-temporarios': typeof AdminAcessosTemporariosRoute
  '/admin_/analytics': typeof AdminAnalyticsRoute
  '/admin_/auditoria': typeof AdminAuditoriaRoute
  '/admin_/auditoria-acessos': typeof AdminAuditoriaAcessosRoute
  '/admin_/auditoria-numeros': typeof AdminAuditoriaNumerosRoute
  '/admin_/cadastro-foto': typeof AdminCadastroFotoRoute
  '/admin_/catalogo': typeof AdminCatalogoRoute
  '/admin_/categorizacao': typeof AdminCategorizacaoRoute
  '/admin_/cesta': typeof AdminCestaRoute
  '/admin_/cesta-auditoria': typeof AdminCestaAuditoriaRoute
  '/admin_/clientes': typeof AdminClientesRoute
  '/admin_/cobertura': typeof AdminCoberturaRouteWithChildren
  '/admin_/consistencia': typeof AdminConsistenciaRoute
  '/admin_/contas': typeof AdminContasRoute
  '/admin_/conversoes': typeof AdminConversoesRoute
  '/admin_/cupom': typeof AdminCupomRoute
  '/admin_/cupom-lote': typeof AdminCupomLoteRoute
  '/admin_/historico-precos': typeof AdminHistoricoPrecosRoute
  '/admin_/ia': typeof AdminIaRoute
  '/admin_/icones-categoria': typeof AdminIconesCategoriaRoute
  '/admin_/image-jobs': typeof AdminImageJobsRoute
  '/admin_/importacoes': typeof AdminImportacoesRoute
  '/admin_/lote-inserir': typeof AdminLoteInserirRoute
  '/admin_/metricas': typeof AdminMetricasRoute
  '/admin_/operacao': typeof AdminOperacaoRoute
  '/admin_/preco-rapido': typeof AdminPrecoRapidoRoute
  '/admin_/precos': typeof AdminPrecosRoute
  '/admin_/promocoes': typeof AdminPromocoesRoute
  '/admin_/promocoes-codigos': typeof AdminPromocoesCodigosRoute
  '/admin_/rank-check': typeof AdminRankCheckRoute
  '/admin_/reports': typeof AdminReportsRoute
  '/admin_/sinonimos': typeof AdminSinonimosRoute
  '/admin_/vitrine': typeof AdminVitrineRoute
  '/admin_/webhooks': typeof AdminWebhooksRoute
  '/c/$shareId': typeof CShareIdRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/comprovante/$id': typeof ComprovanteIdRoute
  '/cotacao/$id': typeof CotacaoIdRoute
  '/estabelecimento/$slug': typeof EstabelecimentoSlugRouteWithChildren
  '/historico/$id': typeof HistoricoIdRoute
  '/historico/produtos': typeof HistoricoProdutosRoute
  '/historico/scans': typeof HistoricoScansRoute
  '/lista_/nova': typeof ListaNovaRoute
  '/lista_/pronta': typeof ListaProntaRoute
  '/loja/$id': typeof LojaIdRouteWithChildren
  '/onde-comprar_/$produto': typeof OndeComprarProdutoRoute
  '/produto-publico/$slug': typeof ProdutoPublicoSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin_/cobertura/$id': typeof AdminCoberturaIdRoute
  '/api/admin/catalog-image': typeof ApiAdminCatalogImageRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/hooks/collab-inbound': typeof ApiPublicHooksCollabInboundRoute
  '/api/public/hooks/drain-catalog-images': typeof ApiPublicHooksDrainCatalogImagesRoute
  '/api/public/hooks/refresh-catalog-images': typeof ApiPublicHooksRefreshCatalogImagesRoute
  '/api/public/hooks/retry-activation-emails': typeof ApiPublicHooksRetryActivationEmailsRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/estabelecimento/$slug/categoria/$category': typeof EstabelecimentoSlugCategoriaCategoryRoute
  '/loja/$id/produto/$slug': typeof LojaIdProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/alertas'
    | '/app'
    | '/assinar'
    | '/assinatura'
    | '/auth'
    | '/buscar'
    | '/cadastro'
    | '/cesta'
    | '/cesta-basica'
    | '/colaborar'
    | '/comparador'
    | '/comparador-ao-vivo'
    | '/comprar-licenca'
    | '/economia'
    | '/estabelecimentos'
    | '/fale-conosco'
    | '/farmacias'
    | '/favoritos'
    | '/financas'
    | '/historico'
    | '/lista'
    | '/login'
    | '/lojista'
    | '/mapa'
    | '/melhores-precos'
    | '/meus-pedidos'
    | '/minha-ia'
    | '/minhas-licencas'
    | '/notificacoes'
    | '/onboarding'
    | '/onde-comprar'
    | '/perfil'
    | '/planos'
    | '/precos'
    | '/precos-por-categoria'
    | '/privacidade'
    | '/resgatar'
    | '/sem-permissao'
    | '/sitemap.xml'
    | '/tendencias'
    | '/admin/gestao'
    | '/admin/acessos-temporarios'
    | '/admin/analytics'
    | '/admin/auditoria'
    | '/admin/auditoria-acessos'
    | '/admin/auditoria-numeros'
    | '/admin/cadastro-foto'
    | '/admin/catalogo'
    | '/admin/categorizacao'
    | '/admin/cesta'
    | '/admin/cesta-auditoria'
    | '/admin/clientes'
    | '/admin/cobertura'
    | '/admin/consistencia'
    | '/admin/contas'
    | '/admin/conversoes'
    | '/admin/cupom'
    | '/admin/cupom-lote'
    | '/admin/historico-precos'
    | '/admin/ia'
    | '/admin/icones-categoria'
    | '/admin/image-jobs'
    | '/admin/importacoes'
    | '/admin/lote-inserir'
    | '/admin/metricas'
    | '/admin/operacao'
    | '/admin/preco-rapido'
    | '/admin/precos'
    | '/admin/promocoes'
    | '/admin/promocoes-codigos'
    | '/admin/rank-check'
    | '/admin/reports'
    | '/admin/sinonimos'
    | '/admin/vitrine'
    | '/admin/webhooks'
    | '/c/$shareId'
    | '/catalogo/$slug'
    | '/categoria/$slug'
    | '/checkout/$id'
    | '/comprovante/$id'
    | '/cotacao/$id'
    | '/estabelecimento/$slug'
    | '/historico/$id'
    | '/historico/produtos'
    | '/historico/scans'
    | '/lista/nova'
    | '/lista/pronta'
    | '/loja/$id'
    | '/onde-comprar/$produto'
    | '/produto-publico/$slug'
    | '/produto/$id'
    | '/produto/$slug'
    | '/admin/cobertura/$id'
    | '/api/admin/catalog-image'
    | '/api/public/mp-webhook'
    | '/api/public/hooks/collab-inbound'
    | '/api/public/hooks/drain-catalog-images'
    | '/api/public/hooks/refresh-catalog-images'
    | '/api/public/hooks/retry-activation-emails'
    | '/api/public/mercadopago/webhook'
    | '/estabelecimento/$slug/categoria/$category'
    | '/loja/$id/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/alertas'
    | '/app'
    | '/assinar'
    | '/assinatura'
    | '/auth'
    | '/buscar'
    | '/cadastro'
    | '/cesta'
    | '/cesta-basica'
    | '/colaborar'
    | '/comparador'
    | '/comparador-ao-vivo'
    | '/comprar-licenca'
    | '/economia'
    | '/estabelecimentos'
    | '/fale-conosco'
    | '/farmacias'
    | '/favoritos'
    | '/financas'
    | '/historico'
    | '/lista'
    | '/login'
    | '/lojista'
    | '/mapa'
    | '/melhores-precos'
    | '/meus-pedidos'
    | '/minha-ia'
    | '/minhas-licencas'
    | '/notificacoes'
    | '/onboarding'
    | '/onde-comprar'
    | '/perfil'
    | '/planos'
    | '/precos'
    | '/precos-por-categoria'
    | '/privacidade'
    | '/resgatar'
    | '/sem-permissao'
    | '/sitemap.xml'
    | '/tendencias'
    | '/admin/gestao'
    | '/admin/acessos-temporarios'
    | '/admin/analytics'
    | '/admin/auditoria'
    | '/admin/auditoria-acessos'
    | '/admin/auditoria-numeros'
    | '/admin/cadastro-foto'
    | '/admin/catalogo'
    | '/admin/categorizacao'
    | '/admin/cesta'
    | '/admin/cesta-auditoria'
    | '/admin/clientes'
    | '/admin/cobertura'
    | '/admin/consistencia'
    | '/admin/contas'
    | '/admin/conversoes'
    | '/admin/cupom'
    | '/admin/cupom-lote'
    | '/admin/historico-precos'
    | '/admin/ia'
    | '/admin/icones-categoria'
    | '/admin/image-jobs'
    | '/admin/importacoes'
    | '/admin/lote-inserir'
    | '/admin/metricas'
    | '/admin/operacao'
    | '/admin/preco-rapido'
    | '/admin/precos'
    | '/admin/promocoes'
    | '/admin/promocoes-codigos'
    | '/admin/rank-check'
    | '/admin/reports'
    | '/admin/sinonimos'
    | '/admin/vitrine'
    | '/admin/webhooks'
    | '/c/$shareId'
    | '/catalogo/$slug'
    | '/categoria/$slug'
    | '/checkout/$id'
    | '/comprovante/$id'
    | '/cotacao/$id'
    | '/estabelecimento/$slug'
    | '/historico/$id'
    | '/historico/produtos'
    | '/historico/scans'
    | '/lista/nova'
    | '/lista/pronta'
    | '/loja/$id'
    | '/onde-comprar/$produto'
    | '/produto-publico/$slug'
    | '/produto/$id'
    | '/produto/$slug'
    | '/admin/cobertura/$id'
    | '/api/admin/catalog-image'
    | '/api/public/mp-webhook'
    | '/api/public/hooks/collab-inbound'
    | '/api/public/hooks/drain-catalog-images'
    | '/api/public/hooks/refresh-catalog-images'
    | '/api/public/hooks/retry-activation-emails'
    | '/api/public/mercadopago/webhook'
    | '/estabelecimento/$slug/categoria/$category'
    | '/loja/$id/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/alertas'
    | '/app'
    | '/assinar'
    | '/assinatura'
    | '/auth'
    | '/buscar'
    | '/cadastro'
    | '/cesta'
    | '/cesta-basica'
    | '/colaborar'
    | '/comparador'
    | '/comparador-ao-vivo'
    | '/comprar-licenca'
    | '/economia'
    | '/estabelecimentos'
    | '/fale-conosco'
    | '/farmacias'
    | '/favoritos'
    | '/financas'
    | '/historico'
    | '/lista'
    | '/login'
    | '/lojista'
    | '/mapa'
    | '/melhores-precos'
    | '/meus-pedidos'
    | '/minha-ia'
    | '/minhas-licencas'
    | '/notificacoes'
    | '/onboarding'
    | '/onde-comprar'
    | '/perfil'
    | '/planos'
    | '/precos'
    | '/precos-por-categoria'
    | '/privacidade'
    | '/resgatar'
    | '/sem-permissao'
    | '/sitemap.xml'
    | '/tendencias'
    | '/admin/gestao'
    | '/admin_/acessos-temporarios'
    | '/admin_/analytics'
    | '/admin_/auditoria'
    | '/admin_/auditoria-acessos'
    | '/admin_/auditoria-numeros'
    | '/admin_/cadastro-foto'
    | '/admin_/catalogo'
    | '/admin_/categorizacao'
    | '/admin_/cesta'
    | '/admin_/cesta-auditoria'
    | '/admin_/clientes'
    | '/admin_/cobertura'
    | '/admin_/consistencia'
    | '/admin_/contas'
    | '/admin_/conversoes'
    | '/admin_/cupom'
    | '/admin_/cupom-lote'
    | '/admin_/historico-precos'
    | '/admin_/ia'
    | '/admin_/icones-categoria'
    | '/admin_/image-jobs'
    | '/admin_/importacoes'
    | '/admin_/lote-inserir'
    | '/admin_/metricas'
    | '/admin_/operacao'
    | '/admin_/preco-rapido'
    | '/admin_/precos'
    | '/admin_/promocoes'
    | '/admin_/promocoes-codigos'
    | '/admin_/rank-check'
    | '/admin_/reports'
    | '/admin_/sinonimos'
    | '/admin_/vitrine'
    | '/admin_/webhooks'
    | '/c/$shareId'
    | '/catalogo/$slug'
    | '/categoria/$slug'
    | '/checkout/$id'
    | '/comprovante/$id'
    | '/cotacao/$id'
    | '/estabelecimento/$slug'
    | '/historico/$id'
    | '/historico/produtos'
    | '/historico/scans'
    | '/lista_/nova'
    | '/lista_/pronta'
    | '/loja/$id'
    | '/onde-comprar_/$produto'
    | '/produto-publico/$slug'
    | '/produto/$id'
    | '/produto/$slug'
    | '/admin_/cobertura/$id'
    | '/api/admin/catalog-image'
    | '/api/public/mp-webhook'
    | '/api/public/hooks/collab-inbound'
    | '/api/public/hooks/drain-catalog-images'
    | '/api/public/hooks/refresh-catalog-images'
    | '/api/public/hooks/retry-activation-emails'
    | '/api/public/mercadopago/webhook'
    | '/estabelecimento/$slug/categoria/$category'
    | '/loja/$id/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AlertasRoute: typeof AlertasRoute
  AppRoute: typeof AppRoute
  AssinarRoute: typeof AssinarRoute
  AssinaturaRoute: typeof AssinaturaRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  CadastroRoute: typeof CadastroRoute
  CestaRoute: typeof CestaRoute
  CestaBasicaRoute: typeof CestaBasicaRoute
  ColaborarRoute: typeof ColaborarRoute
  ComparadorRoute: typeof ComparadorRoute
  ComparadorAoVivoRoute: typeof ComparadorAoVivoRoute
  ComprarLicencaRoute: typeof ComprarLicencaRoute
  EconomiaRoute: typeof EconomiaRoute
  EstabelecimentosRoute: typeof EstabelecimentosRoute
  FaleConoscoRoute: typeof FaleConoscoRoute
  FarmaciasRoute: typeof FarmaciasRoute
  FavoritosRoute: typeof FavoritosRoute
  FinancasRoute: typeof FinancasRoute
  HistoricoRoute: typeof HistoricoRouteWithChildren
  ListaRoute: typeof ListaRoute
  LoginRoute: typeof LoginRoute
  LojistaRoute: typeof LojistaRoute
  MapaRoute: typeof MapaRoute
  MelhoresPrecosRoute: typeof MelhoresPrecosRoute
  MeusPedidosRoute: typeof MeusPedidosRoute
  MinhaIaRoute: typeof MinhaIaRoute
  MinhasLicencasRoute: typeof MinhasLicencasRoute
  NotificacoesRoute: typeof NotificacoesRoute
  OnboardingRoute: typeof OnboardingRoute
  OndeComprarRoute: typeof OndeComprarRoute
  PerfilRoute: typeof PerfilRoute
  PlanosRoute: typeof PlanosRoute
  PrecosRoute: typeof PrecosRoute
  PrecosPorCategoriaRoute: typeof PrecosPorCategoriaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResgatarRoute: typeof ResgatarRoute
  SemPermissaoRoute: typeof SemPermissaoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TendenciasRoute: typeof TendenciasRoute
  AdminAcessosTemporariosRoute: typeof AdminAcessosTemporariosRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminAuditoriaAcessosRoute: typeof AdminAuditoriaAcessosRoute
  AdminAuditoriaNumerosRoute: typeof AdminAuditoriaNumerosRoute
  AdminCadastroFotoRoute: typeof AdminCadastroFotoRoute
  AdminCatalogoRoute: typeof AdminCatalogoRoute
  AdminCategorizacaoRoute: typeof AdminCategorizacaoRoute
  AdminCestaRoute: typeof AdminCestaRoute
  AdminCestaAuditoriaRoute: typeof AdminCestaAuditoriaRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminCoberturaRoute: typeof AdminCoberturaRouteWithChildren
  AdminConsistenciaRoute: typeof AdminConsistenciaRoute
  AdminContasRoute: typeof AdminContasRoute
  AdminConversoesRoute: typeof AdminConversoesRoute
  AdminCupomRoute: typeof AdminCupomRoute
  AdminCupomLoteRoute: typeof AdminCupomLoteRoute
  AdminHistoricoPrecosRoute: typeof AdminHistoricoPrecosRoute
  AdminIaRoute: typeof AdminIaRoute
  AdminIconesCategoriaRoute: typeof AdminIconesCategoriaRoute
  AdminImageJobsRoute: typeof AdminImageJobsRoute
  AdminImportacoesRoute: typeof AdminImportacoesRoute
  AdminLoteInserirRoute: typeof AdminLoteInserirRoute
  AdminMetricasRoute: typeof AdminMetricasRoute
  AdminOperacaoRoute: typeof AdminOperacaoRoute
  AdminPrecoRapidoRoute: typeof AdminPrecoRapidoRoute
  AdminPrecosRoute: typeof AdminPrecosRoute
  AdminPromocoesRoute: typeof AdminPromocoesRoute
  AdminPromocoesCodigosRoute: typeof AdminPromocoesCodigosRoute
  AdminRankCheckRoute: typeof AdminRankCheckRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSinonimosRoute: typeof AdminSinonimosRoute
  AdminVitrineRoute: typeof AdminVitrineRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  CShareIdRoute: typeof CShareIdRoute
  CatalogoSlugRoute: typeof CatalogoSlugRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  ComprovanteIdRoute: typeof ComprovanteIdRoute
  CotacaoIdRoute: typeof CotacaoIdRoute
  EstabelecimentoSlugRoute: typeof EstabelecimentoSlugRouteWithChildren
  ListaNovaRoute: typeof ListaNovaRoute
  ListaProntaRoute: typeof ListaProntaRoute
  LojaIdRoute: typeof LojaIdRouteWithChildren
  OndeComprarProdutoRoute: typeof OndeComprarProdutoRoute
  ProdutoPublicoSlugRoute: typeof ProdutoPublicoSlugRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiAdminCatalogImageRoute: typeof ApiAdminCatalogImageRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicHooksCollabInboundRoute: typeof ApiPublicHooksCollabInboundRoute
  ApiPublicHooksDrainCatalogImagesRoute: typeof ApiPublicHooksDrainCatalogImagesRoute
  ApiPublicHooksRefreshCatalogImagesRoute: typeof ApiPublicHooksRefreshCatalogImagesRoute
  ApiPublicHooksRetryActivationEmailsRoute: typeof ApiPublicHooksRetryActivationEmailsRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tendencias': {
      id: '/tendencias'
      path: '/tendencias'
      fullPath: '/tendencias'
      preLoaderRoute: typeof TendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sem-permissao': {
      id: '/sem-permissao'
      path: '/sem-permissao'
      fullPath: '/sem-permissao'
      preLoaderRoute: typeof SemPermissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resgatar': {
      id: '/resgatar'
      path: '/resgatar'
      fullPath: '/resgatar'
      preLoaderRoute: typeof ResgatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos-por-categoria': {
      id: '/precos-por-categoria'
      path: '/precos-por-categoria'
      fullPath: '/precos-por-categoria'
      preLoaderRoute: typeof PrecosPorCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-comprar': {
      id: '/onde-comprar'
      path: '/onde-comprar'
      fullPath: '/onde-comprar'
      preLoaderRoute: typeof OndeComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-licencas': {
      id: '/minhas-licencas'
      path: '/minhas-licencas'
      fullPath: '/minhas-licencas'
      preLoaderRoute: typeof MinhasLicencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-ia': {
      id: '/minha-ia'
      path: '/minha-ia'
      fullPath: '/minha-ia'
      preLoaderRoute: typeof MinhaIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melhores-precos': {
      id: '/melhores-precos'
      path: '/melhores-precos'
      fullPath: '/melhores-precos'
      preLoaderRoute: typeof MelhoresPrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojista': {
      id: '/lojista'
      path: '/lojista'
      fullPath: '/lojista'
      preLoaderRoute: typeof LojistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmacias': {
      id: '/farmacias'
      path: '/farmacias'
      fullPath: '/farmacias'
      preLoaderRoute: typeof FarmaciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fale-conosco': {
      id: '/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof FaleConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estabelecimentos': {
      id: '/estabelecimentos'
      path: '/estabelecimentos'
      fullPath: '/estabelecimentos'
      preLoaderRoute: typeof EstabelecimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economia': {
      id: '/economia'
      path: '/economia'
      fullPath: '/economia'
      preLoaderRoute: typeof EconomiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar-licenca': {
      id: '/comprar-licenca'
      path: '/comprar-licenca'
      fullPath: '/comprar-licenca'
      preLoaderRoute: typeof ComprarLicencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador-ao-vivo': {
      id: '/comparador-ao-vivo'
      path: '/comparador-ao-vivo'
      fullPath: '/comparador-ao-vivo'
      preLoaderRoute: typeof ComparadorAoVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador': {
      id: '/comparador'
      path: '/comparador'
      fullPath: '/comparador'
      preLoaderRoute: typeof ComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborar': {
      id: '/colaborar'
      path: '/colaborar'
      fullPath: '/colaborar'
      preLoaderRoute: typeof ColaborarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cesta-basica': {
      id: '/cesta-basica'
      path: '/cesta-basica'
      fullPath: '/cesta-basica'
      preLoaderRoute: typeof CestaBasicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cesta': {
      id: '/cesta'
      path: '/cesta'
      fullPath: '/cesta'
      preLoaderRoute: typeof CestaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto-publico/$slug': {
      id: '/produto-publico/$slug'
      path: '/produto-publico/$slug'
      fullPath: '/produto-publico/$slug'
      preLoaderRoute: typeof ProdutoPublicoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-comprar_/$produto': {
      id: '/onde-comprar_/$produto'
      path: '/onde-comprar/$produto'
      fullPath: '/onde-comprar/$produto'
      preLoaderRoute: typeof OndeComprarProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$id': {
      id: '/loja/$id'
      path: '/loja/$id'
      fullPath: '/loja/$id'
      preLoaderRoute: typeof LojaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista_/pronta': {
      id: '/lista_/pronta'
      path: '/lista/pronta'
      fullPath: '/lista/pronta'
      preLoaderRoute: typeof ListaProntaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista_/nova': {
      id: '/lista_/nova'
      path: '/lista/nova'
      fullPath: '/lista/nova'
      preLoaderRoute: typeof ListaNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/scans': {
      id: '/historico/scans'
      path: '/scans'
      fullPath: '/historico/scans'
      preLoaderRoute: typeof HistoricoScansRouteImport
      parentRoute: typeof HistoricoRoute
    }
    '/historico/produtos': {
      id: '/historico/produtos'
      path: '/produtos'
      fullPath: '/historico/produtos'
      preLoaderRoute: typeof HistoricoProdutosRouteImport
      parentRoute: typeof HistoricoRoute
    }
    '/historico/$id': {
      id: '/historico/$id'
      path: '/$id'
      fullPath: '/historico/$id'
      preLoaderRoute: typeof HistoricoIdRouteImport
      parentRoute: typeof HistoricoRoute
    }
    '/estabelecimento/$slug': {
      id: '/estabelecimento/$slug'
      path: '/estabelecimento/$slug'
      fullPath: '/estabelecimento/$slug'
      preLoaderRoute: typeof EstabelecimentoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacao/$id': {
      id: '/cotacao/$id'
      path: '/cotacao/$id'
      fullPath: '/cotacao/$id'
      preLoaderRoute: typeof CotacaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprovante/$id': {
      id: '/comprovante/$id'
      path: '/comprovante/$id'
      fullPath: '/comprovante/$id'
      preLoaderRoute: typeof ComprovanteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$slug': {
      id: '/catalogo/$slug'
      path: '/catalogo/$slug'
      fullPath: '/catalogo/$slug'
      preLoaderRoute: typeof CatalogoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$shareId': {
      id: '/c/$shareId'
      path: '/c/$shareId'
      fullPath: '/c/$shareId'
      preLoaderRoute: typeof CShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/webhooks': {
      id: '/admin_/webhooks'
      path: '/admin/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/vitrine': {
      id: '/admin_/vitrine'
      path: '/admin/vitrine'
      fullPath: '/admin/vitrine'
      preLoaderRoute: typeof AdminVitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/sinonimos': {
      id: '/admin_/sinonimos'
      path: '/admin/sinonimos'
      fullPath: '/admin/sinonimos'
      preLoaderRoute: typeof AdminSinonimosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reports': {
      id: '/admin_/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/rank-check': {
      id: '/admin_/rank-check'
      path: '/admin/rank-check'
      fullPath: '/admin/rank-check'
      preLoaderRoute: typeof AdminRankCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/promocoes-codigos': {
      id: '/admin_/promocoes-codigos'
      path: '/admin/promocoes-codigos'
      fullPath: '/admin/promocoes-codigos'
      preLoaderRoute: typeof AdminPromocoesCodigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/promocoes': {
      id: '/admin_/promocoes'
      path: '/admin/promocoes'
      fullPath: '/admin/promocoes'
      preLoaderRoute: typeof AdminPromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/precos': {
      id: '/admin_/precos'
      path: '/admin/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AdminPrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/preco-rapido': {
      id: '/admin_/preco-rapido'
      path: '/admin/preco-rapido'
      fullPath: '/admin/preco-rapido'
      preLoaderRoute: typeof AdminPrecoRapidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/operacao': {
      id: '/admin_/operacao'
      path: '/admin/operacao'
      fullPath: '/admin/operacao'
      preLoaderRoute: typeof AdminOperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/metricas': {
      id: '/admin_/metricas'
      path: '/admin/metricas'
      fullPath: '/admin/metricas'
      preLoaderRoute: typeof AdminMetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/lote-inserir': {
      id: '/admin_/lote-inserir'
      path: '/admin/lote-inserir'
      fullPath: '/admin/lote-inserir'
      preLoaderRoute: typeof AdminLoteInserirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/importacoes': {
      id: '/admin_/importacoes'
      path: '/admin/importacoes'
      fullPath: '/admin/importacoes'
      preLoaderRoute: typeof AdminImportacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/image-jobs': {
      id: '/admin_/image-jobs'
      path: '/admin/image-jobs'
      fullPath: '/admin/image-jobs'
      preLoaderRoute: typeof AdminImageJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/icones-categoria': {
      id: '/admin_/icones-categoria'
      path: '/admin/icones-categoria'
      fullPath: '/admin/icones-categoria'
      preLoaderRoute: typeof AdminIconesCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/ia': {
      id: '/admin_/ia'
      path: '/admin/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AdminIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/historico-precos': {
      id: '/admin_/historico-precos'
      path: '/admin/historico-precos'
      fullPath: '/admin/historico-precos'
      preLoaderRoute: typeof AdminHistoricoPrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cupom-lote': {
      id: '/admin_/cupom-lote'
      path: '/admin/cupom-lote'
      fullPath: '/admin/cupom-lote'
      preLoaderRoute: typeof AdminCupomLoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cupom': {
      id: '/admin_/cupom'
      path: '/admin/cupom'
      fullPath: '/admin/cupom'
      preLoaderRoute: typeof AdminCupomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/conversoes': {
      id: '/admin_/conversoes'
      path: '/admin/conversoes'
      fullPath: '/admin/conversoes'
      preLoaderRoute: typeof AdminConversoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/contas': {
      id: '/admin_/contas'
      path: '/admin/contas'
      fullPath: '/admin/contas'
      preLoaderRoute: typeof AdminContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/consistencia': {
      id: '/admin_/consistencia'
      path: '/admin/consistencia'
      fullPath: '/admin/consistencia'
      preLoaderRoute: typeof AdminConsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cobertura': {
      id: '/admin_/cobertura'
      path: '/admin/cobertura'
      fullPath: '/admin/cobertura'
      preLoaderRoute: typeof AdminCoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/clientes': {
      id: '/admin_/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cesta-auditoria': {
      id: '/admin_/cesta-auditoria'
      path: '/admin/cesta-auditoria'
      fullPath: '/admin/cesta-auditoria'
      preLoaderRoute: typeof AdminCestaAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cesta': {
      id: '/admin_/cesta'
      path: '/admin/cesta'
      fullPath: '/admin/cesta'
      preLoaderRoute: typeof AdminCestaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/categorizacao': {
      id: '/admin_/categorizacao'
      path: '/admin/categorizacao'
      fullPath: '/admin/categorizacao'
      preLoaderRoute: typeof AdminCategorizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/catalogo': {
      id: '/admin_/catalogo'
      path: '/admin/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AdminCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cadastro-foto': {
      id: '/admin_/cadastro-foto'
      path: '/admin/cadastro-foto'
      fullPath: '/admin/cadastro-foto'
      preLoaderRoute: typeof AdminCadastroFotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/auditoria-numeros': {
      id: '/admin_/auditoria-numeros'
      path: '/admin/auditoria-numeros'
      fullPath: '/admin/auditoria-numeros'
      preLoaderRoute: typeof AdminAuditoriaNumerosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/auditoria-acessos': {
      id: '/admin_/auditoria-acessos'
      path: '/admin/auditoria-acessos'
      fullPath: '/admin/auditoria-acessos'
      preLoaderRoute: typeof AdminAuditoriaAcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/auditoria': {
      id: '/admin_/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/analytics': {
      id: '/admin_/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/acessos-temporarios': {
      id: '/admin_/acessos-temporarios'
      path: '/admin/acessos-temporarios'
      fullPath: '/admin/acessos-temporarios'
      preLoaderRoute: typeof AdminAcessosTemporariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gestao': {
      id: '/admin/gestao'
      path: '/gestao'
      fullPath: '/admin/gestao'
      preLoaderRoute: typeof AdminGestaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/catalog-image': {
      id: '/api/admin/catalog-image'
      path: '/api/admin/catalog-image'
      fullPath: '/api/admin/catalog-image'
      preLoaderRoute: typeof ApiAdminCatalogImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cobertura/$id': {
      id: '/admin_/cobertura/$id'
      path: '/$id'
      fullPath: '/admin/cobertura/$id'
      preLoaderRoute: typeof AdminCoberturaIdRouteImport
      parentRoute: typeof AdminCoberturaRoute
    }
    '/loja/$id/produto/$slug': {
      id: '/loja/$id/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/loja/$id/produto/$slug'
      preLoaderRoute: typeof LojaIdProdutoSlugRouteImport
      parentRoute: typeof LojaIdRoute
    }
    '/estabelecimento/$slug/categoria/$category': {
      id: '/estabelecimento/$slug/categoria/$category'
      path: '/categoria/$category'
      fullPath: '/estabelecimento/$slug/categoria/$category'
      preLoaderRoute: typeof EstabelecimentoSlugCategoriaCategoryRouteImport
      parentRoute: typeof EstabelecimentoSlugRoute
    }
    '/api/public/mercadopago/webhook': {
      id: '/api/public/mercadopago/webhook'
      path: '/api/public/mercadopago/webhook'
      fullPath: '/api/public/mercadopago/webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/retry-activation-emails': {
      id: '/api/public/hooks/retry-activation-emails'
      path: '/api/public/hooks/retry-activation-emails'
      fullPath: '/api/public/hooks/retry-activation-emails'
      preLoaderRoute: typeof ApiPublicHooksRetryActivationEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-catalog-images': {
      id: '/api/public/hooks/refresh-catalog-images'
      path: '/api/public/hooks/refresh-catalog-images'
      fullPath: '/api/public/hooks/refresh-catalog-images'
      preLoaderRoute: typeof ApiPublicHooksRefreshCatalogImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/drain-catalog-images': {
      id: '/api/public/hooks/drain-catalog-images'
      path: '/api/public/hooks/drain-catalog-images'
      fullPath: '/api/public/hooks/drain-catalog-images'
      preLoaderRoute: typeof ApiPublicHooksDrainCatalogImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/collab-inbound': {
      id: '/api/public/hooks/collab-inbound'
      path: '/api/public/hooks/collab-inbound'
      fullPath: '/api/public/hooks/collab-inbound'
      preLoaderRoute: typeof ApiPublicHooksCollabInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminGestaoRoute: typeof AdminGestaoRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGestaoRoute: AdminGestaoRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HistoricoRouteChildren {
  HistoricoIdRoute: typeof HistoricoIdRoute
  HistoricoProdutosRoute: typeof HistoricoProdutosRoute
  HistoricoScansRoute: typeof HistoricoScansRoute
}

const HistoricoRouteChildren: HistoricoRouteChildren = {
  HistoricoIdRoute: HistoricoIdRoute,
  HistoricoProdutosRoute: HistoricoProdutosRoute,
  HistoricoScansRoute: HistoricoScansRoute,
}

const HistoricoRouteWithChildren = HistoricoRoute._addFileChildren(
  HistoricoRouteChildren,
)

interface AdminCoberturaRouteChildren {
  AdminCoberturaIdRoute: typeof AdminCoberturaIdRoute
}

const AdminCoberturaRouteChildren: AdminCoberturaRouteChildren = {
  AdminCoberturaIdRoute: AdminCoberturaIdRoute,
}

const AdminCoberturaRouteWithChildren = AdminCoberturaRoute._addFileChildren(
  AdminCoberturaRouteChildren,
)

interface EstabelecimentoSlugRouteChildren {
  EstabelecimentoSlugCategoriaCategoryRoute: typeof EstabelecimentoSlugCategoriaCategoryRoute
}

const EstabelecimentoSlugRouteChildren: EstabelecimentoSlugRouteChildren = {
  EstabelecimentoSlugCategoriaCategoryRoute:
    EstabelecimentoSlugCategoriaCategoryRoute,
}

const EstabelecimentoSlugRouteWithChildren =
  EstabelecimentoSlugRoute._addFileChildren(EstabelecimentoSlugRouteChildren)

interface LojaIdRouteChildren {
  LojaIdProdutoSlugRoute: typeof LojaIdProdutoSlugRoute
}

const LojaIdRouteChildren: LojaIdRouteChildren = {
  LojaIdProdutoSlugRoute: LojaIdProdutoSlugRoute,
}

const LojaIdRouteWithChildren =
  LojaIdRoute._addFileChildren(LojaIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AlertasRoute: AlertasRoute,
  AppRoute: AppRoute,
  AssinarRoute: AssinarRoute,
  AssinaturaRoute: AssinaturaRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  CadastroRoute: CadastroRoute,
  CestaRoute: CestaRoute,
  CestaBasicaRoute: CestaBasicaRoute,
  ColaborarRoute: ColaborarRoute,
  ComparadorRoute: ComparadorRoute,
  ComparadorAoVivoRoute: ComparadorAoVivoRoute,
  ComprarLicencaRoute: ComprarLicencaRoute,
  EconomiaRoute: EconomiaRoute,
  EstabelecimentosRoute: EstabelecimentosRoute,
  FaleConoscoRoute: FaleConoscoRoute,
  FarmaciasRoute: FarmaciasRoute,
  FavoritosRoute: FavoritosRoute,
  FinancasRoute: FinancasRoute,
  HistoricoRoute: HistoricoRouteWithChildren,
  ListaRoute: ListaRoute,
  LoginRoute: LoginRoute,
  LojistaRoute: LojistaRoute,
  MapaRoute: MapaRoute,
  MelhoresPrecosRoute: MelhoresPrecosRoute,
  MeusPedidosRoute: MeusPedidosRoute,
  MinhaIaRoute: MinhaIaRoute,
  MinhasLicencasRoute: MinhasLicencasRoute,
  NotificacoesRoute: NotificacoesRoute,
  OnboardingRoute: OnboardingRoute,
  OndeComprarRoute: OndeComprarRoute,
  PerfilRoute: PerfilRoute,
  PlanosRoute: PlanosRoute,
  PrecosRoute: PrecosRoute,
  PrecosPorCategoriaRoute: PrecosPorCategoriaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResgatarRoute: ResgatarRoute,
  SemPermissaoRoute: SemPermissaoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TendenciasRoute: TendenciasRoute,
  AdminAcessosTemporariosRoute: AdminAcessosTemporariosRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminAuditoriaAcessosRoute: AdminAuditoriaAcessosRoute,
  AdminAuditoriaNumerosRoute: AdminAuditoriaNumerosRoute,
  AdminCadastroFotoRoute: AdminCadastroFotoRoute,
  AdminCatalogoRoute: AdminCatalogoRoute,
  AdminCategorizacaoRoute: AdminCategorizacaoRoute,
  AdminCestaRoute: AdminCestaRoute,
  AdminCestaAuditoriaRoute: AdminCestaAuditoriaRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminCoberturaRoute: AdminCoberturaRouteWithChildren,
  AdminConsistenciaRoute: AdminConsistenciaRoute,
  AdminContasRoute: AdminContasRoute,
  AdminConversoesRoute: AdminConversoesRoute,
  AdminCupomRoute: AdminCupomRoute,
  AdminCupomLoteRoute: AdminCupomLoteRoute,
  AdminHistoricoPrecosRoute: AdminHistoricoPrecosRoute,
  AdminIaRoute: AdminIaRoute,
  AdminIconesCategoriaRoute: AdminIconesCategoriaRoute,
  AdminImageJobsRoute: AdminImageJobsRoute,
  AdminImportacoesRoute: AdminImportacoesRoute,
  AdminLoteInserirRoute: AdminLoteInserirRoute,
  AdminMetricasRoute: AdminMetricasRoute,
  AdminOperacaoRoute: AdminOperacaoRoute,
  AdminPrecoRapidoRoute: AdminPrecoRapidoRoute,
  AdminPrecosRoute: AdminPrecosRoute,
  AdminPromocoesRoute: AdminPromocoesRoute,
  AdminPromocoesCodigosRoute: AdminPromocoesCodigosRoute,
  AdminRankCheckRoute: AdminRankCheckRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSinonimosRoute: AdminSinonimosRoute,
  AdminVitrineRoute: AdminVitrineRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  CShareIdRoute: CShareIdRoute,
  CatalogoSlugRoute: CatalogoSlugRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  ComprovanteIdRoute: ComprovanteIdRoute,
  CotacaoIdRoute: CotacaoIdRoute,
  EstabelecimentoSlugRoute: EstabelecimentoSlugRouteWithChildren,
  ListaNovaRoute: ListaNovaRoute,
  ListaProntaRoute: ListaProntaRoute,
  LojaIdRoute: LojaIdRouteWithChildren,
  OndeComprarProdutoRoute: OndeComprarProdutoRoute,
  ProdutoPublicoSlugRoute: ProdutoPublicoSlugRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiAdminCatalogImageRoute: ApiAdminCatalogImageRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicHooksCollabInboundRoute: ApiPublicHooksCollabInboundRoute,
  ApiPublicHooksDrainCatalogImagesRoute: ApiPublicHooksDrainCatalogImagesRoute,
  ApiPublicHooksRefreshCatalogImagesRoute:
    ApiPublicHooksRefreshCatalogImagesRoute,
  ApiPublicHooksRetryActivationEmailsRoute:
    ApiPublicHooksRetryActivationEmailsRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
